name: Build, Sign and Deploy Image

on:
  push:
    branches:
      - main

jobs:
  build-and-test-image:
    name: Build and Test Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Trivy
        run: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list
          sudo apt-get update && sudo apt-get install -y trivy
      
      - name: Build Docker image
        run: cd app/ && docker build -t giropops-chainguard .
      
      - name: Run Trivy to scan image
        run: trivy image giropops-chainguard

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image to Docker Hub
        run: |
          docker tag giropops-chainguard ${{ secrets.DOCKER_USERNAME }}/giropops-chainguard:${{ GITHUB.SHA }}
          docker push ${{ secrets.DOCKER_USERNAME }}/giropops-chainguard:${{ GITHUB.SHA }}

  sign-docker-image:
    name: Sign Docker Image
    runs-on: ubuntu-20.04
    needs: build-and-test-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cosign
        run: |
          curl -sL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 --output cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/cosign
      
      - name: Import Cosign Key
        run: echo "${{ secrets.COSIGN_KEY }}" | base64 -d > cosign.key

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASS }}
        run: |
          export COSIGN_EXPERIMENTAL="1"
          cosign sign --key cosign.key ${{ secrets.DOCKER_USERNAME }}/giropops-chainguard:${{ GITHUB.SHA }} --yes

  deploy-and-test-image:
    name: Deploy Image
    runs-on: ubuntu-20.04
    needs: sign-docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy Container
        run: |
          docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/giropops-chainguard:${{ GITHUB.SHA }}
          echo "Container ID: $container_id"

      - name: Install Cosign
        run: |
          curl -sL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 --output cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/cosign
      
      - name: Import Cosign Public Key
        run: echo "${{ secrets.COSIGN_PUBLIC_KEY }}" | base64 -d > cosign.pub

      - name: Verify Image Signature
        run: |
          export COSIGN_EXPERIMENTAL="1"
          cosign verify --key cosign.pub ${{ secrets.DOCKER_USERNAME }}/giropops-chainguard:${{ GITHUB.SHA }} --yes

      - name: Test Container
        run: |
          echo "Verificando tamanho da imagem..."
          docker images
          echo "Validando conteúdo do Site..."
          if ! curl -sS 127.0.0.1:5000 >/dev/null 2>&1; then
            echo "Erro: Falha ao conectar ao serviço."
            exit 1
          else
            echo "Sucesso: Serviço disponível."
          fi
